// <?PHP
// NAMESPACE TVUSTAT;

// FINAL CLASS COMPETITIONONLYIDS EXTENDS COMPETITION
// {

//     PUBLIC STATIC FUNCTION CREATE(INT $NAMEID, INT $LOCATIONID, \DATETIME $DATE, STRING $ID = NULL)
//     {
//         ECHO $NAMEID . ", " . $LOCATIONID . ", " . DATEFORMATUTILS::FORMATDATEFORBL($DATE);
//         $LOCATION = NEW COMPETITIONLOCATION("NV", "NV", $LOCATIONID);
//         $NAME = NEW COMPETITIONNAME("NV", $NAMEID);
//         RETURN NEW COMPETITION($NAME, $LOCATION, $DATE, $ID = NULL);
//     }
// }

